#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }

# Create a temp. dir.
tmpDir=$(mktemp -d -t XXXX) # Works on both OSX and Linux; note: dir. name will have random extension on OSX (e.g., '.../XXXX.bJViLcM3') and none on Linux (e.g., '.../vXDA')
trap 'rm -rf "$tmpDir"' EXIT # Set up exit trap to automatically clean up the temp dir.

# Copy fixtures to temp. dir.
cp -R ./.fixtures/* "$tmpDir/" || die

# Change to temp dir.
cd "$tmpDir" || die


for f in file folder; do
  
  # Set custom icon.
  fileicon set "$f" img.png || die "Failed to set for '$f'"

  # Extract it.
  fileicon get -f "$f" || die "Failed to extract from '$f'"
  outFile=${f}.icns

  # Verify extraction.
  [[ -f $outFile && -s $outFile ]] || die "'$outFile' wasn't created for '$f' or is empty."

done

exit 0
